# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.5
  allure: ayte/allure@0.1.3
jobs:
  ui-chrome-test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to openjdk version of your application.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:11.0
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      # Install web browsers
      - browser-tools/install-browser-tools
      # Install Allure report
      - allure/install
      # Checkout the code
      - checkout
      # Restore cache to speed up build
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      # Run maven test
      - run:
          name: Start E2E Chrome testing
          command: mvn clean verify -Dgroups="GoogleSearch"
      # Generate Allure report
      - run:
          name: Generate Allure report
          command: allure generate target/allure-results --clean --output allure-report
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # Store Allure report
      - store_artifacts:
          name: Uploading Allure report
          path: allure-report

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - ui-chrome-test:
          filters:
            branches:
              only:
                - main